apiVersion: v1
kind: Service
metadata:
  name: birthdaymate-service
  labels:
    app: birthdaymate
spec:
  type: ClusterIP
  selector:
    app: birthdaymate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

